apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  type: NodePort
  selector:
    app: main-server
  ports:
    - protocol: TCP
      port: 5000      
      targetPort: 8000
      nodePort: 31000
