apiVersion: v1
kind: Service
metadata:
  name: main-service
spec:
  type: NodePort
  selector:
    app: main-server
  ports:
    - protocol: TCP
      port: 6000      
      targetPort: 9000
      nodePort: 31000
